// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT PanelConfgiWIFI

lv_obj_t * ui_PanelConfgiWIFI_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PanelConfgiWIFI;
    cui_PanelConfgiWIFI = lv_dropdown_create(comp_parent);
    lv_dropdown_set_options(cui_PanelConfgiWIFI, "Option 1\nOption 2\nOption 3");
    lv_obj_set_width(cui_PanelConfgiWIFI, 150);
    lv_obj_set_height(cui_PanelConfgiWIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_PanelConfgiWIFI, 3);
    lv_obj_set_y(cui_PanelConfgiWIFI, 18);
    lv_obj_set_align(cui_PanelConfgiWIFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_PanelConfgiWIFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANELCONFGIWIFI_NUM);
    children[UI_COMP_PANELCONFGIWIFI_PANELCONFGIWIFI] = cui_PanelConfgiWIFI;
    lv_obj_add_event_cb(cui_PanelConfgiWIFI, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PanelConfgiWIFI, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_PanelConfgiWIFI_create_hook(cui_PanelConfgiWIFI);
    return cui_PanelConfgiWIFI;
}

